language: rust
addons:
  apt:
    packages:
    - libdiscid0-dev
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
- rustup component add rustfmt
script:
  - cargo build
  - cargo test --verbose
  - cargo fmt --verbose --all -- --check
