language: rust
dist: xenial
addons:
  apt:
    packages:
    - libdiscid-dev
rust:
- stable
- beta
- nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_script:
- rustup component add rustfmt
- rustup component add clippy
script:
- cargo build
- cargo test --verbose
- cargo fmt --verbose --all -- --check
- cargo clippy -- -D warnings
deploy:
  provider: cargo
  token:
    secure: dQ2gPVrQT4iukU8CvYKn5UodMRM3EGWD8Y+4turIbaXE5Huny3HI9W3iK4xVdNqLKDe+IQbimQ87JDcPHlakUZAn4hKYU+IXUKsTHJmtEyL9dKhGzz4eNe+lNkdSw6pE+JSJxLLOo2D3dpKUxhRo6CUmc3wX8XvedBjirZNKfSDTiB+H0FCayDGu23KvvharDD3swEkuQbXSqm604i5FeLoNtzvChDKPML+Yc68O5upjnqYJZmqjeXBWhjkd628KnYM6f6nmHQs+TMVgvBeAri6PUs9biVi8JVW8LSWzieZroGWW0YdcqUDxjbNYvIGrpOz3EZqqss77sxIZxyRlw0lMajN51d5Xz9E8GqRnfkCaP9zBObrNjWapce4IF0VgXe4gzXMNCBMfhltTA/sDaUzktAIGzeXTdFOb+cSV0LyvD8yE+dJzUEKaa4NklDN8dQcGOEdLMmIsS8wU5oxaQ89mUCzaLaUQowSWdHgDqW+ZJJaP84hVpDfGHxyB7tnEi1jvwhqSjzKcUZypraE7xpNmQ1jWg0QVV3JbxchswWnqkqVaR/sCzpfFwSytTbNWd+FEqjQbGqV0PK2y1yuqkWoypNMnh81NdeBbJ7RzRa3FpfAIpYHG5hN7j7cx5je7xhElD8EhYQvB0I9W23PbedHVQQbeBJAbOOQZAv60RZQ=
  on:
    branch: master
    tags: true
    rust: stable
